### ISSUE TITLE
Make it work for Niagara script

### ISSUE THREAD

**Issue by hugoattal** [hugoattal/ElectronicNodes#10]
Add Niagara script support.

**Comment by TheHerobrine** [comment]
Well, it seems to be pretty complicated as Niagara is a plugin and not properly part of the engine :/ ...

**Comment by hugoattal** [comment]
I managed to make it work with Niagara :D !!!

**Comment by hugoattal** [comment]
Done!
![image](https://user-images.githubusercontent.com/4563971/113713556-c7491780-96e7-11eb-8dc5-e0264cb49d83.png)
