### ISSUE TITLE
Support for Control Rig

### ISSUE THREAD

**Issue by permelin** [hugoattal/ElectronicNodes#23]
I love your plugin, but it seems to not activate with Control Rig graphs? While that is still an experimental feature in the form of a plugin, it is very much usable already and some of us are developing for it.

**Comment by lucastucious** [comment]
I think that's, like niagara, impossible because it is a plugin

Lucas Peter

**Comment by TheHerobrine** [comment]
Yes, as Lucas stated, this is not possible yet...

Here's what happen with "standard" blueprints:
```
1. Default wire style
2. Electronic nodes wire style injection
```

Here's what happen with "plugins" blueprints:
```
1. Default wire style
2. Electronic nodes wire style injection
3. Plugin wire style injection
```

So the plugin define the wire style AFTER Electronic Nodes. And based of my knowledge, it's not possible to bypass it yet without recompiling the whole engine. Here's two possible ways I can bypass that:

- Either I find a big C++ hack to bypass it (I didn't find one yet)
- Or the Unreal Engine evolve to be able to inject the wire style after the plugin

**Comment by hugoattal** [comment]
Done!

![image](https://user-images.githubusercontent.com/4563971/113713666-e647a980-96e7-11eb-8878-825f3e7ebbd5.png)
