### ISSUE TITLE
Connections disappear in control rig graph

### ISSUE THREAD

**Issue by AtelierAmber** [hugoattal/ElectronicNodes#29]
**Describe the bug**
Selecting nodes in control rig graph causes connections to disappear. 

**To Reproduce**
1. Make some connections in a control rig
2. Highlight the connected nodes

**Expected behavior**
The connections don't disappear.

**Screenshots**
![image](https://user-images.githubusercontent.com/22966571/114113391-b4774400-989b-11eb-8bfd-7342aae114fc.png)
![image](https://user-images.githubusercontent.com/22966571/114113399-b6d99e00-989b-11eb-8c9f-473af7779f65.png)

**Environment (please complete the following information):**
 - UE 4.26.1
 - Windows 64bit

**Additional context**
Only happens in the control rig graph from what I could tell.

**Comment by hugoattal** [comment]
Weird... I managed to reproduce, I'm on it! Sorry for this...

**Comment by hugoattal** [comment]
Fixed, and we get back the wire color feature!
![image](https://user-images.githubusercontent.com/4563971/114193375-bf3ee100-994e-11eb-94b8-aeeb7569c014.png)
