### ISSUE TITLE
Connections disappear in Animation State Machine

### ISSUE THREAD

**Issue by AtelierAmber** [hugoattal/ElectronicNodes#31]
**Describe the bug**

**To Reproduce**
It's easiest to just open the 3rd person example
Open ThirdPerson_AnimBP
Open the default animation state machine (Animation Graphs -> AnimGraph -> Default)
Connections aren't there

**Screenshots**
![image](https://user-images.githubusercontent.com/22966571/114208243-81c06080-991a-11eb-8c25-d827794c598e.png)

**Environment (please complete the following information):**
 - UE 4.26.1
 - Windows 64bit

**Additional context**

**Comment by hugoattal** [comment]
Yes, sorry for this, it's already fixed and waiting for deploy...
cf https://github.com/hugoattal/ElectronicNodes/issues/28

**Comment by AtelierAmber** [comment]
No problem, glad you fixed it.
