### ISSUE TITLE
Hidden connection arrows in State Machine view with Logic Driver plugin

### ISSUE THREAD

**Issue by lihomanovdv** [hugoattal/ElectronicNodes#36]
Electronic Nodes plugin conflicts with Logic Driver Plugin.
Logic Driver StateMachine view doesn't have any connection node visual.

1. Install Logic Driver plugin
2. Create or open a StateMachine asset
3. Try to make any connection on State Machine graph
4. See no connection is drawn.

**Expected behavior**
In-plugin style State Machine connections are visible (Electronic Nodes override style / Logic Driver native style)

**Screenshots**
![image](https://user-images.githubusercontent.com/16917409/115013818-34179b00-9eba-11eb-9d42-2934e42ea9e1.png)

**Environment (please complete the following information):**
 - Unreal Engine version: 4.26
 - Operating System: Windows 10 64bits

**Comment by hugoattal** [comment]
@lihomanovdv Hum, there might be two solutions here...

1 - Make sure that Electronic Nodes is up to date. This has been a bug in state machine and it is solved in 3.2. (cf https://github.com/hugoattal/ElectronicNodes/issues/28). To check the current version of Electronic Nodes, got to Edit/Plugins, find Electronic Nodes and the version should be in the top right corner.

2 - If it's the last version, then it might indeed conflict with this plugins. Then I suggest you go to Edit/Editor Configuration, and disable "HotPatch" in the Electronic Nodes settings. Then restart your editor.

Did any of the two solutions solve the problem?

**Comment by hugoattal** [comment]
Ok, after talking with the Logic Driver creator, you might need to disable the "HotPatch" feature to fix this temporary. In the meantime, I'll try to fix this for it to work with the hotpatch.

**Comment by hugoattal** [comment]
So, after some more digging, the creator of Logic Drive will handle it ;)
https://trello.com/c/wSHN8XtG/151-support-electronic-nodes-32

**Comment by lihomanovdv** [comment]
Ah! Okay, thank you very much for the information!
*--*
*С уважением,*
*Лихоманов Даниил | Автор и основатель курсов UNREALSKILLS*

Phone: +7(912) 688-58-62
Website: www.unrealskills.ru
E-mail: ***@***.***


сб, 17 апр. 2021 г. в 20:58, Hugo ATTAL ***@***.***>:
