### ISSUE TITLE
Better organization of many in-nodes

### ISSUE THREAD

**Issue by elamhut** [hugoattal/ElectronicNodes#38]
After using the plugin for quite a while now I gotta say that I love it and I've been recommending to everyone that wants a more organized blueprint. The text below is my only issue with the plugin and something that really really bothers me and I hope you can solve it :)

Would it be possible to have a better treatment of in-nodes? Currently it's common to have a situation that looks like this:

<img width="445" alt="UE4Editor_Jb4T8Q8TNN" src="https://user-images.githubusercontent.com/36922414/119230722-da774180-baf3-11eb-94ef-d36de77a6872.png">

But when you drag the node a bit further we can have a MUCH cleaner look like this:

<img width="416" alt="UE4Editor_sR3gVcL31t" src="https://user-images.githubusercontent.com/36922414/119230733-e9f68a80-baf3-11eb-9d1f-39247b03023a.png">

Even tho the second effect could be achieved in the first image the plugin currently doesn't do a very good job at untangling these situations. And in those cases we could end up with very unnecessary space between our nodes just to have a cleaner look.

**Comment by hugoattal** [comment]
@elamhut Thank you very much for the kind words 🙂 !

Hum, have you try the "Ribbon" feature?
![image](https://user-images.githubusercontent.com/4563971/119231903-5a68d000-bb23-11eb-8b65-7ec403fcc0f3.png)

It's available under "Edit/Editor Preferences/Electronic Nodes".

**Comment by hugoattal** [comment]
Quick before/after to illustrate:
![image](https://user-images.githubusercontent.com/4563971/119232023-eda20580-bb23-11eb-8eba-09a30ff4f3ca.png)
![image](https://user-images.githubusercontent.com/4563971/119232035-fa265e00-bb23-11eb-9bfc-64778d6dc538.png)

**Comment by elamhut** [comment]
Yes but the problem with ribbons is that the more you try to increase the offset the more they get inside the node. If there was another control to push them out it would be better. Because the way the ribbon works still clumps the wires too much.


![MoiZe9At22](https://user-images.githubusercontent.com/36922414/119235104-34cdcd80-bb07-11eb-899a-651379da8f67.gif)

**Comment by hugoattal** [comment]
Hum, you could increase the "**Horizontal Offset**", but that would affect every wires 😕...
You could also set the "**Wire Alignment**" to left, but once a gain, it's not solving the core problem.

The fact that it sometimes pushes the wires inside the nodes is actually one of the reason I added the "_experimental_" to **Ribbon Style**. The thing is that wires are actually drawn one by one in a random order and I can't do much about it.

I actually might have an idea to force the push outside the nodes though, would that work for you?
Also, do you have in mind a perfect solution for the general problem, regardless of if it's possible or not?

**Comment by elamhut** [comment]
I would think of doing something like this. I don't know if you can detect when this much overlap occurs but when you detect a 90o angle going inside a node you could always force that node to have a Straight line then a 45o angle in the direction of the connection. 

<img width="670" alt="Photoshop_27B9NUVu5l" src="https://user-images.githubusercontent.com/36922414/119242576-534abd80-bb35-11eb-955a-248b6eb14e59.png">

Then you can increase the straight line connecting the node with an offset.
For instance imagine that the image above has:
Target (blue) would have a straight line going into the node of size 1+0
Start Pos line is 1+1
Start Tangent 1+2
etc... So each straight line is slightly longer.

**Comment by hugoattal** [comment]
Hum, I see what you mean, I'll try to do that and keep you posted on 🤔

**Comment by hugoattal** [comment]
@elamhut Done, it will be available in the next update!

Without ribbon
![image](https://user-images.githubusercontent.com/4563971/121803510-54f23780-cc42-11eb-9946-c8012bc3b698.png)

With ribbon
![image](https://user-images.githubusercontent.com/4563971/121803524-62a7bd00-cc42-11eb-8be4-216195f727a7.png)

With ribbon and push outside
![image](https://user-images.githubusercontent.com/4563971/121803539-72270600-cc42-11eb-94b4-e600a24a12c0.png)
