### ISSUE TITLE
Experimental UE5 support

### ISSUE THREAD

**Issue by hugoattal** [hugoattal/ElectronicNodes#39]
Since more and more people want to use Electronic Nodes on UE5, I'm adding experimental support to it.

As UE5 is not production ready (nor the marketplace allow official support of it), it's just experimental, meaning it could break at any UE5 update.

**Comment by hugoattal** [comment]
Done, will be available in the next update

![image](https://user-images.githubusercontent.com/4563971/121806017-41e56480-cc4e-11eb-9cb3-bcd1c737f8f1.png)

**Comment by flankey** [comment]
Hi @hugoattal, how do you activate it on UE5? It tells me that it was built for 4.26 and won't load.

**Comment by hugoattal** [comment]
@flankey You'll need to compile it yourself. You just have to follow this guide: https://github.com/hugoattal/ElectronicNodes/wiki/How-to-install-Electronic-Nodes-on-previous-version-of-the-engine%3F-On-custom-build%3F

To sum it up:
- Download the 3.3 version of Electonic Nodes (available for 4.25 or 4.26) from the Epic Games launcher
- Locate the plugin in your `Engine/Plugins/Marketplace` folder
- Copy the plugin inside the plugins folder of your UE5 project
- Edit the `EngineVersion` of `ElectronicNodes.uplugin` to `"5.0.0"`
- Launch your project (your project must be C++ based for the compilation to happen*)

*If your project in BP-based, just create a C++ class in it and delete it. It won't change anything for you

Keep in mind that the support is experimental for now and might break with future versions of UE5

**Comment by JinVeiss** [comment]
Hello, I've been struggling with this process for a while as a new user. I can't get Unreal to let me create and open a C++ project. 
This is the error that I get:
ERROR: Expecting to find a type to be declared in a module rules named ‘HIDUE’ in UE5Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null. This type must derive from the ‘ModuleRules’ type defined by Unreal Build Tool.

I’ve installed several components with the Visual Studio installer that I’ve seen referenced in forum posts where people couldn’t create a C++ project including:
.Net Core, ASP, Unreal Engine Installer(game development workload), .Net Compiler, .Net build tools and some others.

**Comment by hugoattal** [comment]
@JinVeiss Hum, Unreal Engine is still in preview so there may be some things that are a bit broken... Let's try this:
- Create a brand new blank C++ project
- Follow the previous steps of installing Electronic Nodes in that project

Would this work? If it is, then the problem lies in the conversion of your project to a C++ based one 😕...

**Comment by JinVeiss** [comment]
I get that error shortly after clicking the create button on a C++ project and then Visual Studio opens instead of the Unreal editor. 

This is the full string:
Running C:/Program Files/Epic Games/UE_5.0EA/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.exe Development Win64 -Project="C:/Users/Veiss/Documents/Unreal Projects/Cstuff1/Cstuff1.uproject" -TargetType=Editor -Progress -NoEngineChanges -NoHotReloadFromIDE
Win64 using Manual SDK 10.0.18362.0
Creating makefile for Cstuff1Editor (no existing makefile)
ERROR: Expecting to find a type to be declared in a module rules named 'HIDUE' in UE5Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.  This type must derive from the 'ModuleRules' type defined by Unreal Build Tool.

If all else fails could I provide proof of purchase for a precompiled version?

**Comment by hugoattal** [comment]
Well it seems like it's a UE5 related bug then 😕... I can't really help with that... I think I recall that I had to download a bunch of dotNet SDK things, you might want to check out the unreal forums for such bug with UE5.
(Also, it seems like you have a "HIDUE" plugin that block everything?)

> If all else fails could I provide proof of purchase for a precompiled version?

I don't think it'll work... In any case, it really is an experimental feature (and I'm already crossing marketplace guidelines with this). Best is to wait for the UE5 release and stick to the UE4 for now, if you can't make a C++ based project work on UE5.

**Comment by JinVeiss** [comment]
Yeah, I'm not sure what that HIDUE is. It could be the 3DConnexion Space Mouse plugin that I have. I'll try removing that.

**Comment by spacemarine658** [comment]
For anyone struggling to compile it in UE5 this helps, just ignore the last step and instead add the compiled files into the plugins folder. 

https://www.youtube.com/watch?v=sC0gnfYzFzU

**Comment by achmad-sudibyo-ps** [comment]
![image](https://user-images.githubusercontent.com/83959253/128625217-d0a1d1f2-a33a-48aa-8e2f-b01973b36744.png)

work flawlessly at 5.0 EA 2, thanks @spacemarine658 and @hugoattal you made blueprint programming great again.
