### ISSUE TITLE
Startup pop-up crashes the engine in Commandlet mode

### ISSUE THREAD

**Issue by avudnez** [hugoattal/ElectronicNodes#43]
**Describe the bug**
Title says it all.

**To Reproduce**
1. Enable the plugin
2. Remove the .ini file used to determine first launch (simulate a first launch)
3. Launch a commandlet

**Expected behavior**
The plugin does not crash the engine.

**Environment (please complete the following information):**
 - Unreal Engine version: 4.26 and 5.00
 - Operating System: Windows 10

**Comment by hugoattal** [comment]
I'm really sorry for this, I really tried to make this popup frictionless...

I tried to set up a commandlet, but I'm not familiar with such a feature.

Here's what I did:
- Download this repo (https://github.com/ue4plugins/CommandletPlugin) and put it inside the Plugins folder of my project
- Create a .bat file to run the commandlet

Here are the versions I tested for the .bat file:
```
"D:\Program Files\Epic Games\UE_4.26\Engine\Binaries\Win64\UE4Editor-Cmd.exe" -project="D:\Library\Documents\Unreal Projects\PluginTestFPS 4.26\PluginTestFPS.uproject" -run=HelloWorld
```
```
"D:\Program Files\Epic Games\UE_4.26\Engine\Binaries\Win64\UE4Editor-Cmd.exe" "D:\Library\Documents\Unreal Projects\PluginTestFPS 4.26\PluginTestFPS.uproject" -run=HelloWorld
```
```
"D:\Program Files\Epic Games\UE_4.26\Engine\Binaries\Win64\UE4Editor-Cmd.exe" "PluginTestFPS 4.26" -run=HelloWorld
```
```
"D:\Program Files\Epic Games\UE_4.26\Engine\Binaries\Win64\UE4Editor-Cmd.exe" "PluginTestFPS" -run=HelloWorld
```
But it always ended with this error:
![image](https://user-images.githubusercontent.com/4563971/124662839-9aa0c980-dea9-11eb-8a6d-86bee881a5b9.png)

Do you have any idea what command line I should use to use the commandlet?

**Comment by CanisHelix** [comment]
I cannot package on a headless Linux server due to the popup, it causes a malloc error with slate. I had the same thing with another plugin (albeit they had it in a separate 'module' so it was easier to disable via the .uproject file). I have since written scripts to remove ElectronicNodes from projects upon submitting to CI/CD servers.

**Comment by avudnez** [comment]
For an example of commandlet that we tried and failed, you can run `UE4Editor.exe <ProjectName> -run=loadpackage [arguments]`.

**Comment by hugoattal** [comment]
@CanisHelix Sorry for that... You could also have disabled the popup in Edit/Editor Preferences/Electronic Nodes
![image](https://user-images.githubusercontent.com/4563971/124903814-a2b15400-dfe4-11eb-8259-4df3f1656815.png)

I'm going to check if the engine is in headless mode before displaying any popup. Again, I'm really sorry it made that much trouble...

**Comment by CanisHelix** [comment]
@hugoattal That might work, I'll see if I can get that flipped in the .ini before the CI/CD runs.

**Comment by hugoattal** [comment]
Ok, so I added a check that might fix the issue
![image](https://user-images.githubusercontent.com/4563971/127023859-8ef68ace-b08d-4a48-b2d4-46a6a6548b1b.png)

Unfortunatly, I wasn't able to test it (or to make  commandlet works), so... finger crossed 🤞 ! It will be able in 3.4 version.
