### ISSUE TITLE
automatically straight wires

### ISSUE THREAD

**Issue by ArkTuberGL** [hugoattal/ElectronicNodes#48]
Is it possible to integrate a function so that wires are always straight? You always have to correct this manually with the "Q" key

**Comment by ArkTuberGL** [comment]
The short video should better explain what I mean
https://i.gyazo.com/018b0e016a2d8dbac4ed945fb87f498c.mp4

**Comment by hugoattal** [comment]
Ok, I get it! Well, it has more to do with how the pins are placed on nodes. If I "force" alignment on wires, the nodes won't be aligned with the grid. The best solution would be to space the pins evenly so that they are aligned with the grid, but I didn't find a way to do that properly yet 😕
