### ISSUE TITLE
Any chance support UE5？

### ISSUE THREAD

**Issue by TheMrBigWill** [hugoattal/ElectronicNodes#49]
I know its too early to ask, But I cant leave this plugns. The original is ruining my eyes.

**Comment by hugoattal** [comment]
It's already UE5-ready, but you'll need to compile it yourself 😉
cf https://github.com/hugoattal/ElectronicNodes/issues/39

**Comment by TheMrBigWill** [comment]
do you have video tutorial for artist

Hugo ATTAL ***@***.***> 于2021年8月23日周一 上午12:26写道：

**Comment by hugoattal** [comment]
@TheMrBigWill Well, someone posted a video for just about that on the issue topic: https://github.com/hugoattal/ElectronicNodes/issues/39#issuecomment-883826753

If you have any trouble following it, just tell me !

**Comment by hugoattal** [comment]
Sent to the marketplace team for approval!
