### ISSUE TITLE
UE5 change to FGraphSplineOverlapResult breaks compilation

### ISSUE THREAD

**Issue by m-y-l-e-s** [hugoattal/ElectronicNodes#51]
**Describe the bug**
The constructor for FGraphSplineOverlapResult now has an additional parameter (bool InCloseToSpline) that was not present in 4.X.  This causes building for UE5 to fail.

**To Reproduce**
1. Download/Install a fresh copy of ElectronicNodes for UE 4.27.0
2. Follow build steps from https://github.com/hugoattal/ElectronicNodes/wiki/How-to-install-Electronic-Nodes-on-previous-version-of-the-engine%3F-On-custom-build%3F for UE 5.0.0 Early Access 2
3. When building fails, logs will show

`    [4/7] Module.ElectronicNodes.cpp
    C:/BUILDPATH/HostProject/Plugins/ElectronicNodes/Source/ElectronicNodes/Private/ENConnectionDrawingPolicy.cpp(151): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'FGraphSplineOverlapResult'
    C:/BUILDPATH/HostProject/Plugins/ElectronicNodes/Source/ElectronicNodes/Private/ENConnectionDrawingPolicy.cpp(151): note: No constructor could take the source type, or constructor overload resolution was ambiguous`

**Expected behavior**
Build completes successfully

**Environment (please complete the following information):**
 - Unreal Engine version: UE 5.0.0 Early Access 2
 - Operating System: Windows 64bits

**Additional context**
I understand that this is not a priority, and it would not make sense to fix this in the baseline as it will break the project for UE_4.X.  I just wanted this documented in case it helps someone else trying to perform this build.

This can be fixed/bypassed by updating ENConnectionDrawingPolicy.cpp line 151:
... = FGraphSplineOverlapResult(..., ..., ..., ..., ...**, false**);
Documentation on the new constructor is here:
https://docs.unrealengine.com/5.0/en-US/API/Editor/GraphEditor/FGraphSplineOverlapResult/
The added item is:
bool InCloseToSpline

**Comment by hugoattal** [comment]
@m-y-l-e-s It seems that you use an old version of Electronic Nodes... This line is now 182 and looks like this:
![image](https://user-images.githubusercontent.com/4563971/133836772-adc93a64-5647-47a4-b55b-039546180da1.png)

Don't forget to update the plugin from the Epic Games Launcher!

**Comment by m-y-l-e-s** [comment]
> @m-y-l-e-s It seems that you use an old version of Electronic Nodes... This line is now 182 and looks like this:
> ![image](https://user-images.githubusercontent.com/4563971/133836772-adc93a64-5647-47a4-b55b-039546180da1.png)
> 
> Don't forget to update the plugin from the Epic Games Launcher!

Hmmm that is very strange.  My EG Launcher does not show an update available right now.  I uninstalled and reinstalled it before posting my initial post.  Maybe a caching issue on my end.  Thank you!

**Comment by hugoattal** [comment]
Yeah, it's not the first time the EG Launcher does weird stuff with updates 😕... Try uninstall, then delete the folder under "[your engine]/Plugins/Marketplace/Electronic Nodes" and then reinstall it.
