### ISSUE TITLE
Master activate switch does not correctly disable the plugin

### ISSUE THREAD

**Issue by keedav** [hugoattal/ElectronicNodes#52]
After disabling the "Master activate switch", the wire styling reverts to the unreal default style, but in the Blueprint editor all wire including value wires becomes white, and every wire gets a white arrow to its end.

![Screenshot](https://user-images.githubusercontent.com/3798143/138037943-af4ea86d-864d-42c2-9153-e51a144f523b.png)

**To Reproduce**
1. Install the plugin from the marketplace to a fresh project with no other plugins
2. Open Editor Preferences -> Electronic Nodes Plugin -> disable Master Activate switch
3. Restart the editor
4. Open or create a Blueprint event graph. Note that the wires are curving as if the plugin had been disabled, but all wires, including value wires became white, and every wire got a white arrow to its end

**Expected behavior**
Pressing the "Master Activate" switch should act as its description. It should deactivate the whole plugin, and the wire styles should completely revert to the unreal engine default.

**Environment:**
 - Unreal Engine: 4.27.0
 - Plugin Version: 3.5
 - Operating System: Windows 64bits

**Additional context**
The "Master Activate" switch correctly worked for in our previous project where the Electronic Nodes version 2.6 was installed. We are working in a team, and some members prefer the Unreal styling while other the Electronic Nodes styling. Previously you were able to disable locally the plugin with "Master Activate" without needing to disable the plugin in .uproject.

**Workaround**
You have to disable "Use Hot Patch" *before* pressing "Master Activate", because "Use Hot Patch" option becomes grayed out when "Master Activate" is disabled. With "Use Hot Patch" disabled, "Master Activate" works correctly.

**Comment by hugoattal** [comment]
Fixed by 3.6 !

**Comment by wxz97121** [comment]
Hi, I'm using UE4.27 and Electronic Node Plugin, so the Epic Games Store install 3.5 for me.
But this bug also bothers me a lot. Would you mind telling how to modify 3.5 code to fix this issue?
Or is there any way to force Epic Game Store download 3.6 for me? Is 3.6 compatible with UE4.27?

**Comment by hugoattal** [comment]
@wxz97121 Soooo, for whatever reason 3.6 only made it to UE5.0... I'm sorry for this, I didn't notice. I'm updating the 4.26 and 4.27 version to 3.6. It should be available in ~24h.

(In the meantime, if you really need it now, you need UE5.0 to download EN3.6)

**Comment by wxz97121** [comment]
> @wxz97121 Soooo, for whatever reason 3.6 only made it to UE5.0... I'm sorry for this, I didn't notice. I'm updating the 4.26 and 4.27 version to 3.6. It should be available in ~24h.
> 
> (In the meantime, if you really need it now, you need UE5.0 to download EN3.6)

Thanks! I will check it out~ 😄
