### ISSUE TITLE
Recompile manually failed on UE5 Preview 2

### ISSUE THREAD

**Issue by Jinhaihan** [hugoattal/ElectronicNodes#56]
Because UE5 Preview 2 had rewrite Control rig, so Code not work on UE5 Preview 2. Does any one has idea on it?

**Comment by hugoattal** [comment]
Electronic Nodes only works experimentally with UE5 EA. I'll wait for UE5 to be officially out before making EN officially compatible with it (since it's only previews for now, and changes can still happen).

**Comment by Jinhaihan** [comment]
> Electronic Nodes only works experimentally with UE5 EA. I'll wait for UE5 to be officially out before making EN officially compatible with it (since it's only previews for now, and changes can still happen).

You are right. Thanks for support.

**Comment by Jinhaihan** [comment]
New version work fine on UE5！
