### ISSUE TITLE
Can't complie C++ project because this pulg-in in ue5

### ISSUE THREAD

**Issue by MortalKim** [hugoattal/ElectronicNodes#57]
Plug in works fine on ue5, and I have a new problem.

I can't post my question on epic launcher and I don't know why(unkown issue...), so I came here.

I can't complie because UnrealEditor-ElectronicNodes.dll can't open.

LINK : fatal error LNK1104.

Sound like UE5 are using this pulg-in so that can not modify this dll file, so have this issue. I need close project and complie in vs/rider, it is so complex.

Any ideas to slove that? thanks

**Comment by hugoattal** [comment]
That's super weird... Could you try to:
- Uninstall the plugin
- Delete the folder `C:\Program Files\Epic Games\UE_5.0\Engine\Plugins\Marketplace\ElectronicNodes` (if it still exists)
- Then re-download the plugin

Sometimes the epic launcher messes up a bit 😕

**Comment by Jinhaihan** [comment]
> 

Ahhh, It is not working. 
`LINK : fatal error LNK1104: cannot open file '..\Plugins\Marketplace\ElectronicNodes\Binaries\Win64\UnrealEditor-ElectronicNodes.dll'`
I had reinstall plugin and also have this. My project is a c++ project.

**Comment by Jinhaihan** [comment]
I tried move plugin form engine dir to project/plugin, And it working.
Plugin can complie and work fine in project/plugin and can't complie in engine.

**Comment by hugoattal** [comment]
Hum, that's weird... I'll try to replicate...

**Comment by hugoattal** [comment]
I just tried packaging a test app with the 3.6 version of Electronic Nodes on UE5 and didn't have any problem.
![image](https://user-images.githubusercontent.com/4563971/163848699-01f4844c-7449-4bee-b32e-18ba7a13c10d.png)

![image](https://user-images.githubusercontent.com/4563971/163848473-016da604-299c-48e7-8435-77492687d8bb.png)

I you (or anyone) come across this problem with the last version of Electronic Nodes (3.6), could you please write me a step-by-step instruction to reproduce? (What do you target, what kind of release, etc...)

Thank you and sorry for this!

**Comment by Jinhaihan** [comment]
Nice work! Thanks for quick support

**Comment by hugoattal** [comment]
I just saw that a bug regarding compilation with marketplace plugin was fixed by 5.0.1, so this update might fix your problem if you're still having it: https://forums.unrealengine.com/t/5-0-1-hotfix-released/533481
