### ISSUE TITLE
Plugin need to be compiled at every compilation

### ISSUE THREAD

**Issue by B10v1** [hugoattal/ElectronicNodes#59]
Hi,
I have two bugs, but one is already reported here (_plugin not found on compile from C++/IDE but working within the editor_) ( **#57** )

The other bug is that the engine need to compile Electronic Nodes everytime i compile with LiveCoding (_because i cannot compile from C++, it's say "cannot open file UnrealEditor-ElectronicNodes.dll" or something like that_)

It says that the plugin files "was modified or is new" (_like on the screenshot below_) and compile it everytime, but i can last up to 5-10 seconds (_instead of almost-instant compile without Electronic Nodes_)

![image](https://user-images.githubusercontent.com/83862259/163656546-f83ec822-31d6-409a-bb94-c21075f0af7c.png)

 - Unreal Engine version: 5.0
 - Operating System: Windows 10 64 bits

Maybe it was already like this on the previous engine version ?? But on 4.27 with Darker Nodes & Electronic Nodes the compile time was really quick, and, with the same project, and only Electronic Nodes, it last much longer when Electronic Node is activated.

Thanks !

**Comment by hugoattal** [comment]
That's super weird... It shouldn't have been like this for the last version of the engine, and it might be a UE5 bug, but I'm looking into it.

Out of curiosity, what IDE do you use? (Probably Visual Studio or Rider, but which one?)

**Comment by B10v1** [comment]
I'm using Visual Studio 2022 !

**Comment by Variann** [comment]
I'm having a similar issue. With the 5.0 official release of the plugin I need to compile every single time.

Rider 2021.3.1
Windows 10
Fresh project and fresh engine install.

**Comment by hugoattal** [comment]
I spent a good amount of time investigating this, reverse engineering the live coding feature, etc... but couldn't find any lead yet...

I've asked on the forum with very little hope:
https://forums.unrealengine.com/t/why-my-plugin-is-being-recompiled-on-each-live-coding-compilation/532702
If you guys have any suggestion or idea, that could be super useful!

I'll continue searching until I find a solution, this is not a normal behavior and it's quite painful.

**Comment by hugoattal** [comment]
Okayyyy, it seems to be an engine bug: https://forums.unrealengine.com/t/why-does-ue5-compile-every-module-every-time/521356
So little I can do for now...

But you can fix this temporary by using `bUsePrecompiled = true` in the plugin `.Build.cs` file which located here:
`Epic Games\UE_5.0\Engine\Plugins\Marketplace\ElectronicNodes\Source\ElectronicNodes`

source: https://forums.unrealengine.com/t/why-does-ue5-compile-every-module-every-time/521356/6?u=herobrine20xx

**Comment by B10v1** [comment]
Oh nice it's working !

Thanks !

**Comment by hugoattal** [comment]
This might be fixed by 5.0.1 since it contains fixes regarding marketplace plugins...
https://forums.unrealengine.com/t/5-0-1-hotfix-released/533481
