### ISSUE TITLE
Broken in UE 5.1 Preview1

### ISSUE THREAD

**Issue by franklzt** [hugoattal/ElectronicNodes#63]
**Describe the bug**

 Found that in UE 5.1 preview1 the "unresolved external symbol error" message show up when build the plugin in project as list: 

  unresolved external symbol "public: __cdecl FAnimGraphConnectionDrawingPolicy::FAnimGraphConnectionDrawingPolicy(int,int,float,class FSlateRect const &,class FSlateWindowElementList &,class UEdGraph *)" (??0FAnimGraphConnectionDrawingPolicy@@QEAA@HHMAEBVFSlateRect@@AEAVFSlateWindowElementList@@PEAVUEdGraph@@@Z) referenced in function "public: virtual class FConnectionDrawingPolicy * __cdecl FENConnectionDrawingPolicyFactory::CreateConnectionPolicy(class UEdGraphSchema const *,int,int,float,class FSlateRect const &,class FSlateWindowElementList &,class UEdGraph *)const " (?CreateConnectionPolicy@FENConnectionDrawingPolicyFactory@@UEBAPEAVFConnectionDrawingPolicy@@PEBVUEdGraphSchema@@HHMAEBVFSlateRect@@AEAVFSlateWindowElementList@@PEAVUEdGraph@@@Z)
  unresolved external symbol "public: virtual bool __cdecl FAnimGraphConnectionDrawingPolicy::TreatWireAsExecutionPin(class UEdGraphPin *,class UEdGraphPin *)const " (?TreatWireAsExecutionPin@FAnimGraphConnectionDrawingPolicy@@UEBA_NPEAVUEdGraphPin@@0@Z)
  unresolved external symbol "public: virtual void __cdecl FAnimGraphConnectionDrawingPolicy::BuildExecutionRoadmap(void)" (?BuildExecutionRoadmap@FAnimGraphConnectionDrawingPolicy@@UEAAXXZ)
  unresolved external symbol "public: virtual void __cdecl FAnimGraphConnectionDrawingPolicy::DetermineStyleOfExecWire(float &,struct FLinearColor &,bool &,struct FKismetConnectionDrawingPolicy::FTimePair const &)" (?DetermineStyleOfExecWire@FAnimGraphConnectionDrawingPolicy@@UEAAXAEAMAEAUFLinearColor@@AEA_NAEBUFTimePair@FKismetConnectionDrawingPolicy@@@Z)
  unresolved external symbol "public: virtual void __cdecl FAnimGraphConnectionDrawingPolicy::BuildPinToPinWidgetMap(class TMap<class TSharedRef<class SWidget,1>,class FArrangedWidget,class FDefaultSetAllocator,struct TDefaultMapHashableKeyFuncs<class TSharedRef<class SWidget,1>,class FArrangedWidget,0> > &)" (?BuildPinToPinWidgetMap@FAnimGraphConnectionDrawingPolicy@@UEAAXAEAV?$TMap@V?$TSharedRef@VSWidget@@$00@@VFArrangedWidget@@VFDefaultSetAllocator@@U?$TDefaultMapHashableKeyFuncs@V?$TSharedRef@VSWidget@@$00@@VFArrangedWidget@@$0A@@@@@@Z)
  unresolved external symbol "public: virtual void __cdecl FAnimGraphConnectionDrawingPolicy::ApplyHoverDeemphasis(class UEdGraphPin *,class UEdGraphPin *,float &,struct FLinearColor &)" (?ApplyHoverDeemphasis@FAnimGraphConnectionDrawingPolicy@@UEAAXPEAVUEdGraphPin@@0AEAMAEAUFLinearColor@@@Z)
  unresolved external symbol "public: virtual void __cdecl FControlRigConnectionDrawingPolicy::SetIncompatiblePinDrawState(class TSharedPtr<class SGraphPin,1> const &,class TSet<class TSharedRef<class SWidget,1>,struct DefaultKeyFuncs<class TSharedRef<class SWidget,1>,0>,class FDefaultSetAllocator> const &)" (?SetIncompatiblePinDrawState@FControlRigConnectionDrawingPolicy@@UEAAXAEBV?$TSharedPtr@VSGraphPin@@$00@@AEBV?$TSet@V?$TSharedRef@VSWidget@@$00@@U?$DefaultKeyFuncs@V?$TSharedRef@VSWidget@@$00@@$0A@@@VFDefaultSetAllocator@@@@@Z)
  unresolved external symbol "public: virtual void __cdecl FControlRigConnectionDrawingPolicy::ResetIncompatiblePinDrawState(class TSet<class TSharedRef<class SWidget,1>,struct DefaultKeyFuncs<class TSharedRef<class SWidget,1>,0>,class FDefaultSetAllocator> const &)" (?ResetIncompatiblePinDrawState@FControlRigConnectionDrawingPolicy@@UEAAXAEBV?$TSet@V?$TSharedRef@VSWidget@@$00@@U?$DefaultKeyFuncs@V?$TSharedRef@VSWidget@@$00@@$0A@@@VFDefaultSetAllocator@@@@@Z)
  unresolved external symbol "public: virtual void __cdecl FControlRigConnectionDrawingPolicy::BuildPinToPinWidgetMap(class TMap<class TSharedRef<class SWidget,1>,class FArrangedWidget,class FDefaultSetAllocator,struct TDefaultMapHashableKeyFuncs<class TSharedRef<class SWidget,1>,class FArrangedWidget,0> > &)" (?BuildPinToPinWidgetMap@FControlRigConnectionDrawingPolicy@@UEAAXAEAV?$TMap@V?$TSharedRef@VSWidget@@$00@@VFArrangedWidget@@VFDefaultSetAllocator@@U?$TDefaultMapHashableKeyFuncs@V?$TSharedRef@VSWidget@@$00@@VFArrangedWidget@@$0A@@@@@@Z)
  unresolved external symbol "public: virtual void __cdecl FControlRigConnectionDrawingPolicy::DrawPinGeometries(class TMap<class TSharedRef<class SWidget,1>,class FArrangedWidget,class FDefaultSetAllocator,struct TDefaultMapHashableKeyFuncs<class TSharedRef<class SWidget,1>,class FArrangedWidget,0> > &,class FArrangedChildren &)" (?DrawPinGeometries@FControlRigConnectionDrawingPolicy@@UEAAXAEAV?$TMap@V?$TSharedRef@VSWidget@@$00@@VFArrangedWidget@@VFDefaultSetAllocator@@U?$TDefaultMapHashableKeyFuncs@V?$TSharedRef@VSWidget@@$00@@VFArrangedWidget@@$0A@@@@@AEAVFArrangedChildren@@@Z)
  unresolved external symbol "public: virtual void __cdecl FControlRigConnectionDrawingPolicy::DetermineLinkGeometry(class FArrangedChildren &,class TSharedRef<class SWidget,1> &,class UEdGraphPin *,class UEdGraphPin *,class FArrangedWidget * &,class FArrangedWidget * &)" (?DetermineLinkGeometry@FControlRigConnectionDrawingPolicy@@UEAAXAEAVFArrangedChildren@@AEAV?$TSharedRef@VSWidget@@$00@@PEAVUEdGraphPin@@2AEAPEAVFArrangedWidget@@3@Z)
  unresolved external symbol "public: virtual void __cdecl FControlRigConnectionDrawingPolicy::DetermineWiringStyle(class UEdGraphPin *,class UEdGraphPin *,struct FConnectionParams &)" (?DetermineWiringStyle@FControlRigConnectionDrawingPolicy@@UEAAXPEAVUEdGraphPin@@0AEAUFConnectionParams@@@Z)
  12 unresolved externals
  Microsoft.MakeFile.targets(45, 5): [MSB3073] The command "E:\UE_5.1\Engine\Build\BatchFiles\Build.bat UpdatePluginsEditor Win64 Development -Project="E:\BuildOwnX\UpdatePlugins\UpdatePlugins.uproject" -WaitMutex -FromMsBuild" exited with code 6.

**Comment by hugoattal** [comment]
Hum, UE5.1 is not officially supported, so I can't send an update to the marketplace for such version yet... But be sure that Electronic Nodes will be compatible with UE5.1 when the stable version is officially released!
