### ISSUE TITLE
Prepare 5.1 compatibility

### ISSUE THREAD

**Issue by hugoattal** [hugoattal/ElectronicNodes#64]
Seems like 3.6 does not compile on UE5.1

**Comment by lucastucious** [comment]
Seems like Electronic Node have a dependency to ControlRig, but this prevent compilation

**Comment by hugoattal** [comment]
Yes, I believe there were some updates between preview versions... Anyway, this is fixed for the 5.1 compatible version, which has already been sent to the marketplace.

The marketplace team usually take 24-48h to validate it, so it should be available pretty soon :).

**Comment by lucastucious** [comment]
Good to know ! I disable it until EG download it
