### ISSUE TITLE
No icon button  int ue5.1

### ISSUE THREAD

**Issue by tiantianaixuexi** [hugoattal/ElectronicNodes#65]
![image](https://user-images.githubusercontent.com/31758095/216779235-dc0f931e-0165-433a-978f-e3e39f4cdf25.png)

hello , i want to Auto-collate blueprint nodes, but 5.1 does not have those buttons, what should I do

**Comment by hugoattal** [comment]
I'm sorry, I'm not sure to understand what kind of button you're referring to...

The "Collapse" function is in the context menu when you right-click while having some nodes selected
![image](https://user-images.githubusercontent.com/4563971/217037521-342d4e21-3d42-423c-84d1-8297e62380b0.png)

There's also the "auto-hide unrelated nodes" here
![image](https://user-images.githubusercontent.com/4563971/217037785-95702353-ffde-4ee7-a2d4-822d1c814ed9.png)

Please, could you be a bit more specific on what you're looking for? Maybe with a screenshot?
