### ISSUE TITLE
Warning and failure to load global config when global config is turned on.

### ISSUE THREAD

**Issue by nchapmantimberline** [hugoattal/ElectronicNodes#67]
We're getting warnings when global settings are enabled and they don't seem to work.

changing all calls to Loadconfig in ElectronicNodes.cpp to this fixes it:
			const FString UnrealFileName = FConfigCacheIni::NormalizeConfigIniPath(GlobalSettingsFile);
			ElectronicNodesSettings->LoadConfig(nullptr, *UnrealFileName);

**To Reproduce**
Turn on global settings and run the editor/game.

**Expected behavior**
No warnings.

**Comment by hugoattal** [comment]
Sorry for the delay, I'm just back from vacations... What version of the engine are you using?

I'll fix it in the next version!

**Comment by nchapmantimberline** [comment]
We're using 5.1!
________________________________
