### ISSUE TITLE
Global Setting doesn't ask to check out Settings.ini when source control is enabled

### ISSUE THREAD

**Issue by nchapmantimberline** [hugoattal/ElectronicNodes#68]
If you are using global settings and have source control enabled, you need to check out the settings file before saving/deleting it. The plugin currently does not do this, so you have to check it out manually to make it work. Other ini's in Unreal prompt the user to check out the ini when making changes.

**Comment by hugoattal** [comment]
Hum, globals are configuration for **every** unreal projects (and not specific to the current unreal project), so I'm not sure you want to commit it.

But I can hide the warning so that if globals are activated, and there's no global configuration, it actually create a new one. Wdyt?

**Comment by nchapmantimberline** [comment]
Hmm, that's a good point. Essentially, what we want to be able to do is easily set project-level settings for ElectronicNodes, because once you start using it, everyone kinda has to use it because otherwise if a user using the default unreal layout opens one that was laid out assuming electronicnodes, it will look quite messy. So I don't know if that's something we would achieve through the standard editor settings or not!
________________________________

**Comment by hugoattal** [comment]
Well, if you disable global settings, the settings will be on per project basis. It will be saved in the same place others plugins are saved:
`[game dir]/Saved/Config/WindowsEditor/EditorPerProjectUserSettings.ini`

Does it solve your issue?
