### ISSUE TITLE
Says it's Unavailable?

### ISSUE THREAD

**Issue by vekien** [hugoattal/ElectronicNodes#69]
Heyo!, Love this plugin, went to go install it but couldn't find it in my library. When I go to the Marketplace it says Unavailable? 

Hoping it's just epic being silly!

![image](https://github.com/hugoattal/ElectronicNodes/assets/270800/063df6f6-bb0d-4e6c-8666-d97914d8a440)

**Comment by hugoattal** [comment]
Hum, do you have a compatible Unreal Engine version installed?

If yes, that's very probably a problem from the Epic launcher. I would suggest to exit and restart it.

**Comment by vekien** [comment]
Hello,

I have a compatible version, I have 5.2, 5.1 and 4.27.

The weird thing is it doesn't even appear in the Vault, even though I've purchased it.

Several restarts and no luck. The other one works fine (darker nodes)
