### ISSUE TITLE
Plugin prevents MetaSound graph animations from playing

### ISSUE THREAD

**Issue by MekuCube** [hugoattal/ElectronicNodes#71]
**Describe the bug**
MetaSound graph inputs do not show the animated pulse when activated.

**To Reproduce**
1. With plugin enabled, open a MetaSound
2. Hit Play
3. Notice no animations
4. Disable plugin and restart editor.
5. Open a MetaSound
6. Hit Play
7. Notice animations

**Expected behavior**
The MetaSound links should animate while MetaSound is playing.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Unreal Engine version: 5.2.1
 - Operating System: Windows 64bits

**Additional context**
I think it is caused by the following code chunk missing from ``FNodeFactoryPatch::CreateConnectionPolicy_Hook`` (it is present in ``FNodeFactory::CreateConnectionPolicy``):

```cpp
// First give a shot to the registered connection factories
if (!ConnectionDrawingPolicy)
{
	for (TSharedPtr<FGraphPanelPinConnectionFactory> FactoryPtr : FEdGraphUtilities::VisualPinConnectionFactories)
	{
		if (FactoryPtr.IsValid())
		{
			ConnectionDrawingPolicy = FactoryPtr->CreateConnectionPolicy(Schema, InBackLayerID, InFrontLayerID, ZoomFactor, InClippingRect, InDrawElements, InGraphObj);
			if (ConnectionDrawingPolicy)
			{
				break;
			}
		}
	}
}
```

**Comment by MekuCube** [comment]
From further investigation, it looks like this also causes all links to appear as white, when the color should be different depending on the type.

**Comment by hugoattal** [comment]
Sorry for this...

I suggest disabling the "Hot Patch" feature if you want to use Meta Sound with their custom features. (You'll need to restart the engine)

![image](https://github.com/hugoattal/ElectronicNodes/assets/4563971/295dab90-c123-4536-9b6b-833f0f9f4702)

I'm going to fix this in the meantime, it should be available pretty quickly.

**Comment by hugoattal** [comment]
Ok, that's far more difficult than I though, as Metasound is a remote plugin. Meaning either:
- I include all the Metasound source in Electronic Nodes to behave correctly
- I manage to hack a way into getting access to a static private member of class

The second option is what you thought of, it's just that I can't access to `FEdGraphUtilities::VisualPinConnectionFactories`.

I have a few hack to access private member or private method of a class, but none seems to work for  a private static member.

I'll dig a bit more and keep you posted on.

**Comment by hugoattal** [comment]
I tried doing this

```cpp
#define private public
#include "EdGraphUtilities.h"
#undef private
```

(yeah it's ugly, but you have to do what you have to do 😅...)

But it seems that static members are not exported in 5.3, so I get an unresolved external.

**Comment by Setmaster** [comment]
What is lost if hotpatch is disabled?

**Comment by hugoattal** [comment]
@Setmaster You lose the ability to use Electronic Nodes in Plugins blueprints (like Niagara or Control Rigs).

But it does not change anything for "common" blueprints like actor logic or material blueprints.
