### ISSUE TITLE
Can this be used with metasounds? 

### ISSUE THREAD

**Issue by Setmaster** [hugoattal/ElectronicNodes#72]
When I open the metasound's editor it uses the normal line style.

**Comment by MekuCube** [comment]
Not currently supported, and there is a known issue with Metasounds (see here: https://github.com/hugoattal/ElectronicNodes/issues/71)

**Comment by hugoattal** [comment]
If you want to use Electronic Nodes with MetaSound, you can add it inside `Custom Graph Schema`.

![image](https://github.com/hugoattal/ElectronicNodes/assets/4563971/1c184f0b-b4d5-4f01-93f5-ef5d9d133918)

Sadly, as mentioned in #71, you'll lose some features... If you want to keep those features, you have to disable the Hot Patch feature.

I have no solution for this for now, I'll the other issue open 😕
