### ISSUE TITLE
Bubble only for exec nodes

### ISSUE THREAD

**Issue by Lorenz5600** [hugoattal/ElectronicNodes#73]
Hi,

congrats for this plugin, it's brilliant!

I'd like to suggest an option to animate bubbles only for exec nodes (or in general, for certain node types). This would add more contrast to the execution flow and would visualize the flow even better.

Cheers,
Jake

**Comment by hugoattal** [comment]
Done!

![image](https://github.com/hugoattal/ElectronicNodes/assets/4563971/1d64cf2e-4f95-443d-bd26-3a3724f14569)

![image](https://github.com/hugoattal/ElectronicNodes/assets/4563971/84bd9229-9717-451a-bc3d-1a356a66c089)

Will be shipped in next version 😄

**Comment by d0pLeR** [comment]
> Done!
> 
> ![image](https://private-user-images.githubusercontent.com/4563971/297434063-1d64cf2e-4f95-443d-bd26-3a3724f14569.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NDk1OTUsIm5iZiI6MTcwOTY0OTI5NSwicGF0aCI6Ii80NTYzOTcxLzI5NzQzNDA2My0xZDY0Y2YyZS00Zjk1LTQ0M2QtYmQyNi0zYTM3MjRmMTQ1NjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMTQzNDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTIzMmExZTY3NWJlYjQwYWRiOWZkYjQwZmZiN2VkNTNkY2IzOGVkYjE0MGU0NjM0ZTA4YWNlZmY2Mzk5Nzg1NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fBkjU6TWu89wFq2ZdQnvv6zaa3aszgrJKlrivLTxbNs)
> 
> ![image](https://private-user-images.githubusercontent.com/4563971/297433271-84bd9229-9717-451a-bc3d-1a356a66c089.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NDk1OTUsIm5iZiI6MTcwOTY0OTI5NSwicGF0aCI6Ii80NTYzOTcxLzI5NzQzMzI3MS04NGJkOTIyOS05NzE3LTQ1MWEtYmMzZC0xYTM1NmE2NmMwODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMTQzNDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTJjYTVmMTQwOTJhNzUzY2E4YmE3M2EzODYxMjFmZmQ2ZjFlZDI2MDlhMWE2MDY5YTZmYWE4YTUyYjI2ZjE5ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GncjVJ-2ID6pTd94DYn_Kz7XeLyXn3LEM_b5r9R6ydE)
> 
> Will be shipped in next version 😄

amazing
