### ISSUE TITLE
In Control Rig, wire is hidden when internal data from a pin is used in a connection.

### ISSUE THREAD

**Issue by geekrelief** [hugoattal/ElectronicNodes#75]
**Describe the bug**
The wire to an internal data pin is hidden when the encompassing struct pin is collapsed. 

**To Reproduce**
1. Expand a pin that has multiple elements in it.
2. Connect it to another node's pin.
3. Collapse the expanded pin of the first node, and the wire disappears.

**Expected Behavior**
The wire should be present even if the pin with the compound data is collapsed. This is the case when the plugin is disabled.

**Example**
https://github.com/hugoattal/ElectronicNodes/assets/27040/684f3272-d1c9-435c-851e-cbe8ae1264b1

In this example video, I have CR_Mannequin_Body from the Control Rig Examples opened. I'm inside the `Setup Spine` function. Here a Transform's Translation is missing the wire, but when the Transform pin is expanded it appears.

**Environment (please complete the following information):**
 - Unreal Engine version: 5.3.2
 - Operating System: Windows 64bits

**Comment by hugoattal** [comment]
Hey, thank you for writing an issue (and sorry for the late reply).

Well, some graphs added by plugins have custom logic that change the behavior of wires. I'll see if I can replicate this behavior for Control Rigs, but last time I checked, a big refactor of the engine made this pretty difficult...

In the meantime, I suggest disable Hot Patch. It will disable Electronic Nodes on custom plugins graphs (like Control Rig or Niagara), but it will still work on base graphs (like Blueprint and Material).
