### ISSUE TITLE
SVT sample parameter with remap to new range node crashes UE.

### ISSUE THREAD

**Issue by cantcodetho** [hugoattal/ElectronicNodes#76]
As in the subject. Basically SVT nodes are crashing editor with Electronic Nodes enabled in UE 5.3.2. After I disabled plugin I could test SVT nodes just fine. I don't think you even need remap to new range node.

**Comment by hugoattal** [comment]
I'm sorry, I'm not familiar with SVT... In what type of graph are you placing them? Does the crash occur if you disable the Hot Patch feature in the settings of Electronic Nodes?

**Comment by cantcodetho** [comment]
Yes crash happens with hot patch.

Create material. Inside, Add SpalseVolumeTextureSampleParameter node. Drag from its output A and and pick RemapValueRange. Now grab output of RemapValueRange, drag and crash.

**Comment by hugoattal** [comment]
> Yes crash happens with hot patch.

I mean, can you **disable** Hot Patch and let me know if that still crashes?

Thanks for the report, I'll take a look as soon as possible!

**Comment by cantcodetho** [comment]
I derped, I meant that I tried with disabled hot patch and still crashed.

**Comment by hugoattal** [comment]
I managed to reproduce, super weird bug, I'm looking into it...

**Comment by hugoattal** [comment]
Fixed! Will be ship in the next version (couple of days)
![image](https://github.com/hugoattal/ElectronicNodes/assets/4563971/fbcc656f-244e-4807-85eb-8ff78849d029)

**Comment by cantcodetho** [comment]
Cool, thanks.
