### ISSUE TITLE
The editor crashes when attempting to migrate the content of a project

### ISSUE THREAD

**Issue by AbdShak** [hugoattal/ElectronicNodes#78]
**Describe the bug**
The editor crashes when attempting to migrate the content of a project that uses the (ElectronicNodes) plugin to another project.

**To Reproduce**
1. Right-click on the 'Content folder' of a project that uses the (ElectronicNodes) plugin.
2. Choose 'Migrate' and select the destination folder.
3. Engine Crash (Assertion failed: !IsArrayType(TypeIndex) [File:D:\build\++UE5\Sync\Engine\Plugins\Runtime\RigVM\Source\RigVM\Private\RigVMCore\RigVMRegistry.cpp)

**Expected behavior**
The content should be migrated without relying on disabling or enabling a plugin.

**Environment (please complete the following information):**
 - Unreal Engine version: UE 5.3.2
 - Operating System: Windows 10 64bits

**Additional context**
Disabling the plugin resolves the issue; however, there is still uncertainty about why ElectronicNodes depends on RigVM and the origin of the problem.

**Comment by hugoattal** [comment]
Might be linked to https://www.reddit.com/r/unrealengine/comments/t69x9m/ue5_crash_on_asset_migration/ ?

> When migrating the content from the Learning Kit Games project to our project, you will need to click the NO option when this dialog shows up. There is a bug in 5.0 that attempts to copy the Plugin Content along with the Project Content and this will allow you to continue with the course.

Electronic Nodes does not depends on RigVM...

I'm investigating.

**Comment by hugoattal** [comment]
I can't migrate anything from any project, whether it uses Electronic Nodes or not, it simply free my editor 😅...

Could you please try:
- To migrate a file from a brand-new project with only Electronic Nodes activated?
- To migrate a file from your project with the "Hot Patch" feature of Electronic Nodes disabled? (in Editor Settings)

And tell me if those crash aswell?

**Comment by AbdShak** [comment]
Hi Hugoattal,

I attempted to migrate files from a new project with only Electronic Nodes activated, and it went smoothly. Although I removed the Kit content as mentioned in the Reddit thread before trying anything, the migration still failed. I believe the bug report I submitted is now invalid since the migration was successful even with Electronic Nodes activated.

However, there's still one aspect I find puzzling. When you create a new project with only Electronic Nodes and then remove the built-in plugin (RigVM) from the plugins, it triggers a series of warnings for dependency plugins, one of which is (Electronic Nodes). Any insights on why this occurs?


`This plugin is required by ElectronicNodes. Would you like to disable it as well?`

![1](https://github.com/hugoattal/ElectronicNodes/assets/6763076/1602959a-255c-4029-b95d-5f76b0aecfc5)

**Comment by hugoattal** [comment]
Honestly sometimes Unreal just does weird stuff... It's more likely a bug with Unreal. If I can do anything to mitigate the problem, I'll do it, but I honestly don't know what I should do.

I would suggest disabling Electronic Nodes when migrating stuff, I know it's not the ideal solution, I'm sorry 😕...

---

Concerning the `RigVM` dependency, it's actually to make Control Rig graphs work with Electronic Nodes (https://github.com/hugoattal/ElectronicNodes/issues/23). As it's activated by default and unlikely to be disabled, I considered it to be a fair trade for those who want to use Electronic Nodes with Control Rig.

(Yeah, I kinda forgot about it, but Electronic Nodes DOES actually depend on `RigVM`, sorry 😅...)

**Comment by hugoattal** [comment]
Now that I think about it, the new Hot Patch system does not rely on the Control Rig plugin to inject Electronic Nodes, so I should be able to remove it 🤔. I'll do this on the next version!

Thanks for the insight!

**Comment by AbdShak** [comment]
Thank you, Hugoattal. I truly appreciate the clarifications you've provided and all the hard work you've put into this awesome plugin.
