### ISSUE TITLE
No bubble on animation blueprint

### ISSUE THREAD

**Issue by hugoattal** [hugoattal/ElectronicNodes#8]
There're no bubbles on animation blueprint.

![image](https://user-images.githubusercontent.com/4563971/67900382-9ebd0580-fb64-11e9-8813-586e818170cf.png)
![image](https://user-images.githubusercontent.com/4563971/67900409-aaa8c780-fb64-11e9-9252-bcdb1e6267fe.png)

**Comment by TheHerobrine** [comment]
Fixed!

![image](https://user-images.githubusercontent.com/4563971/68079208-704e5d00-fde6-11e9-9c08-b23b7763e0d8.png)

It will be available on the next update ;)

**Comment by wantg** [comment]
5.2.1 does not work

**Comment by Temujiing** [comment]
> 5.2.1 does not work

We had the same, it looks to be related to the zoom level.

**Comment by hugoattal** [comment]
Yes, sorry, it's already fixed, I just need to push the new version to the marketplace (and wait for the Epic team to accept it). I'll do it tomorrow!

**Comment by Temujiing** [comment]
> Yes, sorry, it's already fixed, I just need to push the new version to the marketplace (and wait for the Epic team to accept it). I'll do it tomorrow!

Thanks you!
