### ISSUE TITLE
Unreal 5.4 Preview Support

### ISSUE THREAD

**Issue by srwxr-xr-x** [hugoattal/ElectronicNodes#82]
**Is your feature request related to a problem? Please describe.**
Supported version for Unreal Engine 5.4 Previews

**Describe the solution you'd like**
Release a built version on the store for Unreal Engine 5.4 Preview and the future 5.4 versions!

**Describe alternatives you've considered**

**Additional context**

**Comment by hugoattal** [comment]
Hello!

Don't worry Electronic Nodes will support UE 5.4 🙂, but after the preview phase, as the marketplace doesn't allow uploading a version for a preview version of the engine...
