### ISSUE TITLE
Incorrect warning about not purchasing

### ISSUE THREAD

**Issue by phil-scott-78** [hugoattal/ElectronicNodes#84]
Seems like the check introduced in #83 isn't verifying the purchase properly in all cases. This is in 5.4 and 3.1.2 version of the plugin. I tried removing the plugin from my project and reenabling it, but no dice. Same error.
![image](https://github.com/hugoattal/ElectronicNodes/assets/2447331/948c54ce-aa38-4e60-8217-54c5474646ec)

**Comment by pladux** [comment]
Also clicking "Yes" opens up the Epic Launcher with a 404 page for me.

![image](https://github.com/hugoattal/ElectronicNodes/assets/19801768/278896ec-890e-4a07-99d4-f2423122c959)

**Comment by hugoattal** [comment]
Yes, I noticed it, really sorry for this, I'm fixing it right now 😞... In the meantime, you can just click "No" and move on, it does not change the use of Electronic Nodes.

**Comment by hugoattal** [comment]
Fixed! The new version has been sent to the marketplace, it should be updated in ~24h, really sorry for this...

**Comment by Tackyflea** [comment]
Thanks for your quick response, I had the same issue! Will wait for the update :)

**Comment by hugoattal** [comment]
I really hope that the marketplace team will tackle this quickly, I'm ashamed of annoying so many people with this... I'll send them an email if this is not done by the end of the day.
