### ISSUE TITLE
Remove the (shitty) entitlement check

### ISSUE THREAD

**Issue by hugoattal** [hugoattal/ElectronicNodes#89]
Biggest mistake I've made with Electronic Nodes. (For those reading, I'm really sorry)

This need to be gone in the next version.

In the meantime, you can disable it in Edit/Editor Preferences/Plugin/Electronic Nodes/Debug/Disable Entitlement Check

**Comment by IntXThOrn** [comment]
Hey Hugoattal, I'm using Electronic nodes in 5.4 but there is no option to Disable Entitlement Check, in that location, all I have are activate fallback and display schema name.  Truly frustrating, I was actually about to remove electronic nodes as it delays every window I open by seconds and keep showing me dialogue in between

**Comment by hugoattal** [comment]
@IntXThOrn Hello and sorry for that... The entitlement check has been completely removed, you just have to update Electronic Nodes to the last version (3.14)
