### ISSUE TITLE
Child modal opens EVERYTIME I open my project, please make it stop!

### ISSUE THREAD

**Issue by jamesmandrews** [hugoattal/ElectronicNodes#95]
Everytime I open my 5.5 project I get you advertising modal.  It's really annoying, please make it stop.

**Comment by hugoattal** [comment]
Ok, they had the brilliant idea to rename plugins folder for 5.5 from `ElectronicNodes` to `Electron913898e3acc7V14`... Fixing it!

**Comment by hugoattal** [comment]
Temporary fix: you can disable the popup in Edit/Editor Preferences/Darker Nodes or Electronic Nodes

The setting is called `Activate Popup on Update`.

**Comment by hugoattal** [comment]
This should be fixed on the new version available as soon as the marketplace validate it. (This concern both Electronic Nodes and Darker Nodes)

I let this issue open so that you can confirm that you get the popup only once.

**Comment by pladux** [comment]
I can confirm the issue has been fixed in the latest version. Thanks a lot.

**Comment by jamesmandrews** [comment]
Confirmed it is fixed in both plugins, appreciate the quick fix.
